#!/bin/bash

ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' &
ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' &
ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key -N '' &
/usr/sbin/sshd -D &

cd /root/oj

chmod 744 ./start

echo "source /opt/rh/devtoolset-7/enable" >>/etc/profile
source /etc/profile

./start

while true; do
    echo "111";
    sleep 1;
done